spring.application.name=Praza-Shop
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3306/prazashop?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


application.security.jwt.secret-key=ZmFrZVNlY3JldEtleUhlcmU1NjY2NjY2NjY2NjY2NjY2NjY
application.security.jwt.expiration=900000          
application.security.jwt.refresh-token-expiration=2592000000 